#!/bin/sh
#
# Prevent committing files with trailing whitespace
# Extracted from the pre-commit.sample file in the standard git template

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $REVISION --
